FROM openjdk:17
# ADD target/Unsolo-rockets-0.0.1-SNAPSHOT.jar Unsolo-rockets.jar
ADD /home/runner/work/Unsolo-Travels/Unsolo-Travels/Unsolo-rockets/target/Unsolo-rockets-0.0.1-SNAPSHOT.jar Unsolo-rockets.jar
ENTRYPOINT ["java","-jar","Unsolo-rockets.jar"]
EXPOSE 8080